"""Create or modify classes table

Revision ID: 3e38934cbb3b
Revises: fc11831da259
Create Date: 2025-03-19 18:18:09.433910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e38934cbb3b'
down_revision = 'fc11831da259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_index', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('proficiencies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('saving_throws', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('subclasses', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('spellcasting', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['class_index'])
        batch_op.drop_column('class_features')
        batch_op.drop_column('created_at')
        batch_op.drop_column('skills_profs')
        batch_op.drop_column('primary_ability')
        batch_op.drop_column('spellcasting_ability')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('saving_throws_profs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saving_throws_profs', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('spellcasting_ability', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('primary_ability', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skills_profs', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_features', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('url')
        batch_op.drop_column('spellcasting')
        batch_op.drop_column('subclasses')
        batch_op.drop_column('saving_throws')
        batch_op.drop_column('proficiencies')
        batch_op.drop_column('class_index')

    # ### end Alembic commands ###
