"""Modify spells table

Revision ID: c79f01d74681
Revises: dc8b39091719
Create Date: 2025-03-19 18:02:28.854466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c79f01d74681'
down_revision = 'dc8b39091719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=10), nullable=False))

    with op.batch_alter_table('monster_actions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'monsters', ['monster_id'], ['id'])

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('components',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('materials',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('damage_dice')
        batch_op.drop_column('damage_type')
        batch_op.drop_column('saving_throw')
        batch_op.drop_column('higher_levels')
        batch_op.drop_column('attack_type')
        batch_op.drop_column('created_at')
        batch_op.drop_column('spell_attack_bonus')
        batch_op.alter_column('description', type_=sa.Text())
        batch_op.alter_column('higher_level', type_=sa.Text())

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walk_speed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inspiration', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('current_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temp_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conditions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('initiative', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('discord',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.drop_constraint('users_discord_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_discord_key', ['discord'])
        batch_op.alter_column('discord',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('initiative')
        batch_op.drop_column('armor_class')
        batch_op.drop_column('conditions')
        batch_op.drop_column('defense')
        batch_op.drop_column('temp_hp')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('current_hp')
        batch_op.drop_column('inspiration')
        batch_op.drop_column('walk_speed')

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spell_attack_bonus', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attack_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('higher_levels', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saving_throw', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('damage_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('damage_dice', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.alter_column('materials',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('components',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('description', type_=sa.String(length=255))
        batch_op.alter_column('higher_level', type_=sa.String(length=255))

    with op.batch_alter_table('monster_actions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('discord', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
