"""Add index column to monsters table

Revision ID: dc8b39091719
Revises: 
Create Date: 2025-03-19 16:09:50.631239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc8b39091719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False, server_default='default_password'))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=10), nullable=False))

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.String(length=100), nullable=False, server_default='default_index'))
        batch_op.add_column(sa.Column('monster_index', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('hit_dice', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('hit_points_roll', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proficiencies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('damage_vulnerabilities', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('damage_resistances', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('damage_immunities', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('condition_immunities', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('passive_perception', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proficiency_bonus', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('special_abilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.alter_column('armor_class',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('senses',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('actions',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('legendary_actions',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['index'])
        batch_op.drop_column('monster_type')
        batch_op.drop_column('saving_throws')
        batch_op.drop_column('resistances')
        batch_op.drop_column('vulnerabilities')
        batch_op.drop_column('immunities')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.execute('ALTER TABLE monsters ALTER COLUMN armor_class TYPE JSON USING armor_class::JSON')
        batch_op.execute('ALTER TABLE monsters ALTER COLUMN speed TYPE JSON USING speed::JSON')
        batch_op.execute('ALTER TABLE monsters ALTER COLUMN senses TYPE JSON USING senses::JSON')

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('casting_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('range',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('components',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('concentration',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ritual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('damage',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('spells_index_key', type_='unique')
        batch_op.drop_column('index')
        batch_op.drop_column('url')

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walk_speed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('inspiration', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('current_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temp_hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conditions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('armor_class', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('initiative', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('discord',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.drop_constraint('users_discord_key', type_='unique')

    with op.batch_alter_table('monster_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_id', sa.Integer, sa.ForeignKey('monsters.id'), nullable=False))

    op.create_table(
        'monsters',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('monster_index', sa.String(length=100), nullable=False, unique=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('size', sa.String(length=10), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('alignment', sa.String(length=50), nullable=True),
        sa.Column('armor_class', sa.JSON(), nullable=False),
        sa.Column('hit_points', sa.Integer, nullable=False),
        sa.Column('hit_dice', sa.String(length=20), nullable=False),
        sa.Column('hit_points_roll', sa.String(length=20), nullable=True),
        sa.Column('speed', sa.JSON(), nullable=False),
        sa.Column('strength', sa.Integer, nullable=False),
        sa.Column('dexterity', sa.Integer, nullable=False),
        sa.Column('constitution', sa.Integer, nullable=False),
        sa.Column('intelligence', sa.Integer, nullable=False),
        sa.Column('wisdom', sa.Integer, nullable=False),
        sa.Column('charisma', sa.Integer, nullable=False),
        sa.Column('proficiencies', sa.JSON(), nullable=True),
        sa.Column('damage_vulnerabilities', sa.String(length=200), nullable=True),
        sa.Column('damage_resistances', sa.String(length=200), nullable=True),
        sa.Column('damage_immunities', sa.String(length=200), nullable=True),
        sa.Column('condition_immunities', sa.String(length=200), nullable=True),
        sa.Column('senses', sa.JSON(), nullable=True),
        sa.Column('passive_perception', sa.Integer, nullable=True),
        sa.Column('languages', sa.String(length=200), nullable=True),
        sa.Column('challenge_rating', sa.Float, nullable=False),
        sa.Column('proficiency_bonus', sa.Integer, nullable=False),
        sa.Column('xp', sa.Integer, nullable=False),
        sa.Column('special_abilities', sa.JSON(), nullable=True),
        sa.Column('actions', sa.JSON(), nullable=True),
        sa.Column('legendary_actions', sa.JSON(), nullable=True),
        sa.Column('image_url', sa.String(length=200), nullable=True),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_discord_key', ['discord'])
        batch_op.alter_column('discord',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('initiative')
        batch_op.drop_column('armor_class')
        batch_op.drop_column('conditions')
        batch_op.drop_column('defense')
        batch_op.drop_column('temp_hp')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('current_hp')
        batch_op.drop_column('inspiration')
        batch_op.drop_column('walk_speed')

    with op.batch_alter_table('spells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('index', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('spells_index_key', ['index'])
        batch_op.alter_column('damage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ritual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('concentration',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('components',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('range',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('casting_time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('immunities', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vulnerabilities', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resistances', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saving_throws', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('monster_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('legendary_actions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('actions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('languages',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('senses',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('armor_class',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('special_abilities')
        batch_op.drop_column('xp')
        batch_op.drop_column('proficiency_bonus')
        batch_op.drop_column('passive_perception')
        batch_op.drop_column('condition_immunities')
        batch_op.drop_column('damage_immunities')
        batch_op.drop_column('damage_resistances')
        batch_op.drop_column('damage_vulnerabilities')
        batch_op.drop_column('proficiencies')
        batch_op.drop_column('hit_points_roll')
        batch_op.drop_column('hit_dice')
        batch_op.drop_column('type')
        batch_op.drop_column('index')
        batch_op.drop_column('monster_index')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('discord', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
